#' Get SSURGO Ecological Site Aggregation
#'
#' Performs "all" condition aggregation via `soilDB::get_SDA_coecoclass()` (called iteratively).
#'
#' Suitable for generating aggregate ecological site information for the complete SSURGO database.
#'
#' @param x character. Vector of one or more soil survey area symbols of interest.
#' @param threshold Passed to `soilDB::get_SDA_coecoclass()`. Default: `0` ensuring that all conditions, regardless of aggeregate component percentage, are included.
#' @param ... Additional arguments passed to `soilDB::get_SDA_coecoclass()` (such as for a custom data source via `dsn` argument)
#' @param not_assigned character. Value used for conditions not assigned an ecological site. Default: `NA`
#' @param fillna logical. Fill any `NA` values generated by `data.table::rbindlist(fill=TRUE)` in "site" ID or "name" fields with value of `not_assigned`
#' @export
#' @importFrom soilDB makeChunks get_SDA_coecoclass
#' @importFrom data.table rbindlist
es_aggregate_ssurgo <- function(x, threshold = -100, ..., not_assigned = NA, fillna = TRUE) {
  areasyms <- unique(x)
  chunk <- soilDB::makeChunks(areasyms, size = 500)

  z <- data.table::rbindlist(lapply(1:max(chunk), function(i) {
    soilDB::get_SDA_coecoclass(method = "all",
                               areasymbols = areasyms[chunk == i],
                               threshold = threshold,
                               ...)
  }), fill = TRUE)

  if (isTRUE(fillna)) {
    # fill=TRUE introduces NA for conditions beyond those existing in the data subsets
    fillnacol <- names(z)[grepl("site\\d+[name]*$", names(z))]
    for (f in fillnacol) {
      z[[f]] <- ifelse(is.na(z[[f]]), not_assigned, z[[f]])
    }
  }
  z
}

#' Calculate Aggregate Site Percentage
#'
#' Calculate aggregate site percentage from an "all" condition aggregation. Derived from sum of columns in `x` containing `"pct_r"`
#'
#' @param x a data.frame containing "all" condition aggregation, one row per map unit
#' @param pattern Default: `"pct_r"`
#' @param na.rm Default: `TRUE`; use `FALSE` to return `NA` if any condition is missing a value.
#' @export
#' @return numeric. Sum of values columns containing `"pct_r"` (or other specified `pattern`)
es_calculate_aggregate_sitepct <- function(x, pattern = "pct_r", na.rm = TRUE) {
  rowSums(as.data.frame(x)[grepl(pattern, colnames(x))], na.rm = na.rm)
}

#' Remove Conditions all `"Not assigned"` or `NA`
#'
#' @param x a data.frame containing "all" condition aggregation, one row per map unit
#' @param not_assigned character. Value of `"Not assigned"` condition. Default: `"Not assigned"`
#'
#' @return data.frame, with some columns potentially omitted.
#' @export
es_remove_empty_conditions <- function(x, not_assigned = "Not assigned") {
  x[!apply(x, 2, function(y) all(is.na(y) | y == not_assigned))]
}

#' Parse an Ecological Site or Forage Suitability Group ID
#'
#' @param x character. Vector of site codes to parse. Standard site codes for `ecoclasstypename="NRCS Forestland Site"` and
#' `ecoclasstypename="NRCS Rangeland Site"` for `ecoclassref="Ecological Site Description Database` as well as
#' `ecoclasstypename="Forage Suitability Group"` are `11` characters in length.
#'
#' @return _data.frame_ containing columns `"kind"`, `"mlra"`, `"unit"`, `"number"`, and `"state"`.
#' @export
#'
#' @examples
#' es_decompose_site_code(c("R103XY021MN", "G103XS006MN", "F108XC508IA", NA, "C01948"))
es_decompose_site_code <- function(x) {
  idx.std <- which(nchar(x) != 11)
  x.parts <- gsub("([RFG])(\\d{3})([A-Z]{2})(\\d{3})([A-Z]{2})|(.*)", "\\1;\\2;\\3;\\4;\\5;", x)
  res <- as.data.frame(do.call('rbind', strsplit(x.parts, ";", fixed = TRUE)))
  colnames(res) <- c("kind", "mlra", "unit", "number", "state")
  res[idx.std, ] <- NA
  res
}
